# This workflow is triggered over certain period of time intervals

name: auto_pull

on:
  schedule:
    - cron: '* 3/5 * * *'

jobs:
  auto_pull:
    runs-on: windows-latest
    steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-python@v4
        
        - name: Run automation
          run: python automation.py
