name: Tests

on:
  push
    
jobs:
  test_changes:
    
    runs-on: windows-latest
    
      
    steps:
      - name: Checkout code
      - uses: actions/checkout@v4
      
      
      - name: test changes
      - uses: actions/setup-python@v4
      - run: python .test.py
