name: Tests

on:
  push
    
jobs:
  test_changes:
    
    runs-on: windows-latest
    
      
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          node-version: '20'
      - name: test changes
        run: python .test.py
