name: Tests

on:
  push
    
jobs:
  test_changes:
    
    runs-on: windows-latest
    
      
    steps:
      - name: Checkout code
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
      
      - name: test changes
        run: python .test.py
